### ISSUE TITLE
Merge of hiera hash from >1 yaml backend not working?

### ISSUE THREAD

**Issue by brezynski** [alexharv074/puppet-firewall_multi#11]
Hi - 
Thanks for the module.  Works great and solves a problem for me.  I haven't been able to get the hash merge to work.  I have a hash of firewall rules (firewall_multis) defined in a common yaml file and another hash (same name: firewall_multis) defined in a nodes/%{clientcert} yaml file.

hiera.yaml  looks like this:

```yaml
---
:backends:
  - yaml
:hierarchy:
  - "%{environments}"
  - "nodes/%{clientcert}"
  - common
  - defaults
:merge_behavior: deeper
```

init.pp class looks like this:

```puppet
class tsofirewall (
  Hash $firewall_multis,
) {
  create_resources(firewall_multi, $firewall_multis)
}
```

But when I apply the module/class to a host I only get the hash/firewall_multis from the nodes/%{clientcert}.  If I comment out that hash I then get only the hash from the common.yaml file.  With other modules I have written the hash is merged (as I'd expect and as I want).

Hiera command line returns a merge of the hashes (as I'd expect):
hiera --hash xxxfirewall::firewall_multis environment=test clientcert="nodename.example.com"

Should the module merge the hashes or is there something not working as expected?
Thanks

**Comment by alexharv074** [comment]
Hi @brezynski 

I think the module is working as expected.  In order to get a merged Hash in Puppet 3 you need to use the Hiera_hash function.  Have a look at [this](https://docs.puppet.com/puppet/latest/reference/function.html#hierahash) and let me know if it solves your problem.

**Comment by brezynski** [comment]
Yep - that did it.  I mistakenly thought that declaring 

```puppet
`Hash $firewall_multis`

should do the same as:

```puppet
$firewall_rules=hiera_hash('tsofirewall::firewall_multis'),

But I see it doesn't do that at all - it simply sets (enforces) the data type (Hash) for $firewall_multis.

Using hiera_hash my module is now doing what I want (merging the hashes).

Thanks for your help!

**Comment by alexharv074** [comment]
Yes that's correct, and since you have Puppet 4, also have a look at [this](https://www.devco.net/archives/2016/02/03/puppet-4-data-lookup-strategies.php) blog post.  Thanks for your feedback.
