### ISSUE TITLE
Consider also the IPv4 & IPv6 options

### ISSUE THREAD

**Issue by Wesseldr** [alexharv074/puppet-firewall_multi#12]
Thanks for this nice work!

Consider also an option for doing both IPv4 & IPv6 rules apply at once.
Most consistent way would be through

> provider => ['ip6tables', 'iptables']

Hope that these additions of you get merged into the main branche of puppet firewall

**Comment by alexharv074** [comment]
Hi @Wesseldr 

Can you give me a usage example that shows me how people might use that new feature?

**Comment by Wesseldr** [comment]
Use Case: We run a webserver on the internet. The host has both an IPv4 and an IPv6 address. It's a kind of an odd idea imho that you would have different ports open on ipv6 than on ipv4 so why not combine punching holes in the firewall in one command for both IPv4 and IPv6 stack
However that is the case right now:

Current situation: Open up ports for a webserver
`  
# Setup IPv4 holes in IPv4 firewall:
firewall { '100 allow http and https access':
    dport  => [80, 443],
    proto  => tcp,
    action => accept,
    provider => 'iptables'
}
# Not so much DRY but we need to do this to setup IPv6 holes in firewall:
firewall { '100 allow http and https access':
    dport  => [80, 443],
    proto  => tcp,
    action => accept,
    provider => 'ip6tables'
}
`

Prefered DRY situation:
`  
# DRY example of setup IPv4 & IPv6 holes firewall:
firewall { '100 allow http and https access':
    dport  => [80, 443],
    proto  => tcp,
    action => accept,
    provider => ['ip6tables', 'iptables']
}
`

**Comment by alexharv074** [comment]
Ok, that makes sense. Sure, I'll implement that. Give me a day or two.

**Comment by alexharv074** [comment]
Ok, looks like I only needed 36 minutes. Version 1.5.0 is released! Thanks for your feature suggestion.

**Comment by Wesseldr** [comment]
Holy Crap! Do you fly around with a big S on your shirt ? 👍 
Thanks man! going to give it a go! awsome!
