### ISSUE TITLE
r10k keeps reinstalling module

### ISSUE THREAD

**Issue by RiverHeart** [alexharv074/puppet-firewall_multi#22]
Hola,

First off, thanks for your module, it's been very helpful and reliable! I have an issue where r10k keeps reinstalling firewall_multi whenever it runs. I searched and [found this issue](https://github.com/elastic/puppet-elastic-stack/issues/19) which indicated that r10k might have an issue with forge releases containing a .git file. Any chance that's the case here?

Thanks for your time!

**Comment by alexharv074** [comment]
Hi @RiverHeart , oddly enough you seem to be right that this module is packaging up its .git directory and I didn't know. I'll see if anyone knows why that is since I always just followed the standard instructions for building the Forge module.

**Comment by alexharv074** [comment]
@RiverHeart , I have released 1.14.1 that doesn't have this problem. Does that resolve your issue?

**Comment by RiverHeart** [comment]
Hey Alex,

Sorry for the delay getting back to you. Happy to say that the issue is fixed :)
