### ISSUE TITLE
Missing tag for v1.14.1

### ISSUE THREAD

**Issue by runejuhl** [alexharv074/puppet-firewall_multi#23]
Hi @alexharv074 

Thank you for `firewall_multi`! I noticed that the latest release, [v.1.14.1](https://github.com/alexharv074/puppet-firewall_multi/commit/aa14b8c468c209f2c54fad9cadd73cc640479c26), is missing a tag. Could I get you to add one?

Thanks in advance!

**Comment by alexharv074** [comment]
Hi @runejuhl  oops fixed. Thanks.
