### ISSUE TITLE
Server Error: no parameter named 'zone'

### ISSUE THREAD

**Issue by rmalenko** [alexharv074/puppet-firewall_multi#24]
Hell Alex,

I have the error 
```
Error 500 on SERVER: Server Error: no parameter named 'zone' (file: .../rnd/modules/firewall_multi/manifests/init.pp, line: 259) 
```

**Comment by alexharv074** [comment]
Hi @rmalenko Isn't this the same issue you saw once before - I documented the workaround here https://github.com/alexharv074/puppet-firewall_multi#error-no-parameter-named-x

**Comment by rmalenko** [comment]
Hi Alex
I use 
The latest version of Firewall and Firewall multi from GitHub. Puppet version is 6.12.0

**Comment by alexharv074** [comment]
Hi @rmalenko , all the same I haven't changed this module in a long time, perhaps consider asking for help on the Puppet Community Slack? I don't believe there is an issue with the module.
