### ISSUE TITLE
Support for puppetlabs/firewall 2.4.0

### ISSUE THREAD

**Issue by cFire** [alexharv074/puppet-firewall_multi#26]
Recently a new version of the `puppetlabs/firewall` module was published which includes a fix for a rather annoying bug on Debian based systems so I'm quite keen to upgrade that module. Thus it would be very nice if support could be added for the 2.4.0 version of the module.

**Comment by alexharv074** [comment]
hi @cFire , sorry I forgot to reply but 2.4.0 support was release a week or so ago. Thanks for the reminder!

**Comment by cFire** [comment]
> hi @cFire , sorry I forgot to reply but 2.4.0 support was release a week or so ago. Thanks for the reminder!

No problem. Thanks for your continued work on the module!
