### ISSUE TITLE
No parameter named 'condition'

### ISSUE THREAD

**Issue by juokelis** [alexharv074/puppet-firewall_multi#29]
Hi, tried to run with 1.20.0, firewall 2.8.0 and got:

`Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: no parameter named 'condition' (file: /etc/puppetlabs/code/environments/development/modules/firewall_multi/manifests/init.pp, line: 303) on Firewall[120 accept nrpe from xx.xx.xx.xx] (file: /etc/puppetlabs/code/environments/development/modules/firewall_multi/manifests/init.pp, line: 303) on node yy.yy.yy`

Downgraded firewall multi to 1.19.0 keeping firewall at 2.8.0 now everything runs smoothly. 
Tested on puppetserver 6.12.1-1buster, puppet-agent 6.16.0-1buster, both on Debian 10 (Buster)

**Comment by fetzerms** [comment]
I am having the same issue. Downgrading to 1.19.0 did not work for me, as it was complaining about other parameters.
A downgrade of the firewall module to 2.5.0 did the job for me.

**Comment by fetzerms** [comment]
I tried the same, but I actually had to go back to 1.18.0, because it was complaining about "notrack" then.

**Comment by alexharv074** [comment]
@juokelis , @fetzerms  This is nearly always caused by this https://github.com/alexharv074/puppet-firewall_multi#error-no-parameter-named-x

**Comment by fetzerms** [comment]
@alexharv074 I was using this with 1.20.0 and firewall 2.8.0, just as defined by the metadata.json. Going back to 1.18.0 and keeping firewall 2.8.0 solved the issue for me.

**Comment by juokelis** [comment]
Looks like it's running properly with 1.20.0 and 2.8.1

**Comment by hoene** [comment]
1.20.0 and 2.8.1 does not work for me :-(

**Comment by hoene** [comment]
Puppet does not like all those parameters. I removed them having only the ones I am using.

<pre>
# @summary A defined type wrapper for spawning
#   [puppetlabs/firewall](https://github.com/puppetlabs/puppetlabs-firewall)
#   resources for arrays of certain inputs.
#
# @param [Array] source An array of source IPs or CIDRs.
# @param [Array] destination An array of destination IPs or CIDRs.
# @param [Array] proto An array of protocols.
# @param [Array] icmp An array of ICMP types.
# @param [Array] provider An array of providers.
# 
define firewall_multi (
  $ensure                      = undef,
  $provider                    = undef,
  $action                      = undef,
  $jump         = undef,
  $proto = undef,
  $chain = undef,
  $outiface = undef,
  $destination = undef,
  $source = undef,
  $table = undef,
) {   

  $firewalls = firewall_multi(      
    {   
      $name => {
        ensure                      => $ensure,
        provider                    => $provider,
        action                      => $action,
        jump => $jump, 
        proto => $proto,
        chain => $chain,
        outiface => $outiface,
        destination => $destination,
        source => $source,
        table => $table,
      }
    }
  )

  create_resources(firewall, $firewalls)
}
</pre>

**Comment by stefanlasiewski** [comment]
As Alex said, you need to apply the workaround for this as discussed in https://github.com/alexharv074/puppet-firewall_multi#error-no-parameter-named-x .

The workarounds are:

* Use r10k with a hook to enable "Environment isolation"
* If you don't use r10k, then for every environment, purge the types an regenerate them like so:

```
rm -rf /etc/puppetlabs/code/environments/<your environment>/.resource_types/

puppet generate types --environment <your environment> --environmentpath /etc/puppetlabs/code/environments/
Notice: Generating Puppet resource types.
```

This is a frustrating bug, but it's due to how Puppet works internally.

**Comment by fetzerms** [comment]
@stefanlasiewski thank you very much! This actually solved my problem. I am currently planning the move to r10k. Somehow I wasnt sure that I needed to actually remove the resource_types before regenerating them.

**Comment by brightdroid** [comment]
> 1.20.0 and 2.8.1 does not work for me

Works for me too, which does not work is firewall v3.0.0

**Comment by alexharv074** [comment]
@brightdroid 
What does not work in firewall v3.0.0?

**Comment by brightdroid** [comment]
Sry for the long delay.
Re-checked now and everything works for me.
