### ISSUE TITLE
puppet compability in version 3.0.0 (Puppet >= 3.0.0 < 6.0.0)

### ISSUE THREAD

**Issue by kinocz** [alexharv074/puppet-firewall_multi#32]
Maybe I'm missing something here, but is there particular reason this module is limited to older versions of puppet?

my tests show it works OK with puppet 7.x and debian 10/11, just editor is complaining about being not compatible

```
    alexharvey-firewall_multi =3.0.0 was resolved to Forge alexharvey-firewall_multi-3.0.0, which depends on
      Puppet >= 3.0.0 < 6.0.0Puppet
```

**Comment by alexharv074** [comment]
@kinocz  Fixed in version 3.5.0 just released. Thanks for bringing this to my attention.
