### ISSUE TITLE
Firewall 5.0.0 support

### ISSUE THREAD

**Issue by moritzdietz** [alexharv074/puppet-firewall_multi#35]
Knowing the last commit to this repository has been a while back, I still wanted to task whether you'd be able and willing to add support for puppetlabs-firewall 5.0.0.

**Comment by alexharv074** [comment]
@moritzdietz I have added version 5.0.0 support in the master branch but I'm having trouble releasing to Puppet Forge. 

```
alexharvey@192-168-1-105 puppet-firewall_multi % bundle exec rake module:push          

Built /Users/alexharvey/git/home/puppet-firewall_multi/pkg/alexharvey-firewall_multi-5.0.0.tar.gz
Uploading to Puppet Forge alexharvey/firewall_multi
rake aborted!
Blacksmith::Error: Error uploading firewall_multi to the forge https://forgeapi.puppetlabs.com/v3/releases [401 Unauthorized]: {
  "message": "401 Unauthorized",
  "errors": [
    "This request requires valid Authorization"
  ]
}
```

I tried resetting my password. Will look again later.

**Comment by moritzdietz** [comment]
Awesome! Thank you for looking into this and your continued work on it.

**Comment by alexharv074** [comment]
Ok I think you should be able to install that now.

**Comment by moritzdietz** [comment]
Thank you!
