### ISSUE TITLE
no parameter named 'connlimit_upto'

### ISSUE THREAD

**Issue by jlindquist-godaddy** [alexharv074/puppet-firewall_multi#43]
We aren't using this parameter directly, but I started to get an error about  `connlimit_upto` after doing some wider testing with the latest 7.0.2 release

```
Puppet Server Error: no parameter named 'connlimit_upto' (file: /etc/puppetlabs/code/puppet-control/dev/modules/firewall_multi/manifests/init.pp, line: 306)
```

with a sample resource such as the following (if that helps):
```
firewall_multi { '090 Allow SSH Access':
    proto  => 'tcp',
    action => accept,
    dport  => 22,
    source => [
      '10.1.2.3/32',
      '10.2.3.4/32',
      ...
    ],
  }
```

**Comment by alexharv074** [comment]
@jlindquist-godaddy that's a bit odd. That one's there? https://github.com/alexharv074/puppet-firewall_multi/blob/master/manifests/init.pp#L27

**Comment by jlindquist-godaddy** [comment]
Yeah, I'm still trying to troubleshoot what's going on, so I may have been a bit premature on this one. I setup a separate test and can't replicate it, but once I merged this and the firewall upgrade into our main branches, it started popping up with that error.  Having other issues related to https://github.com/puppetlabs/puppetlabs-firewall/issues/1162 which are compounding the problem.  Will follow-up one I have more info, apologies

**Comment by alexharv074** [comment]
@jlindquist-godaddy there's a well-known caching issue that is documented in the README that can impact this module. I can't remember the details but have a look.

**Comment by jlindquist-godaddy** [comment]
👍🏻 I suspected something with the environment isolation may be at play, and will probably investigate some more tomorrow.  Thank you for the pointer, and for being so responsive during all this too

**Comment by jlindquist-godaddy** [comment]
I think this will be ok, I can't replicate it anymore, and must have just been a caching issue in one of the environments.  I'll close this out
