### ISSUE TITLE
Firewall 7.0.3: parameter issue

### ISSUE THREAD

**Issue by moritzdietz** [alexharv074/puppet-firewall_multi#44]
We just updated to the latest version of your module and the firewall module – 7.0.2 and 7.0.3 respectively.

After that we noticed the following in our reports:
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Firewall_multi[000 accept all icmp]: has no parameter named 'action'
```
We then checked the firewall docs: https://forge.puppet.com/modules/puppetlabs/firewall/reference#policy
So it seems that `action` was replaced by `policy`.

After changing our rule to say:
```
contoso_base::firewall::pre::rules:
  '000 accept all icmp':
    policy: 'accept'
    proto: 'icmp'
```
This hash is handled in a manifest like so:
```
create_resources(firewall_multi, $rules)
```

it still reported an issue, this time it said `policy` is no known parameter
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Firewall_multi[000 accept all icmp]: has no parameter named 'policy'
```
I'm a bit stumped now. Am I using the module wrong or is there something missing?

**Comment by robertc99** [comment]
Actually the replacement for action is jump.
https://github.com/puppetlabs/puppetlabs-firewall/pull/1145

**Comment by moritzdietz** [comment]
Ah, perfect! Thank you for the hint. :)
