### ISSUE TITLE
Suggestion: Alias example on readme.

### ISSUE THREAD

**Issue by claflico** [alexharv074/puppet-firewall_multi#8]
Please add this answer as an example on your readme: http://stackoverflow.com/questions/36561572/puppet-using-yamls-with-puppetlabs-firewall/36562379#36562379

I just spent 4+ hours trying to figure out how to specify an array of subnets in common.yaml and then reference them in a role.yaml file as the source for a firewall rule. Searching led me to your module but I still couldn't get it to work because of the hiera array to string issue. I had given up but in a different search somehow ended up on that page.

Using source: "%{alias('mylocaldomain')}" solved my problem....kudos sir....kudos.

**Comment by alexharv074** [comment]
Thanks @claflico   that's a great suggestion, and sorry I didn't think of it earlier.

**Comment by alexharv074** [comment]
Updated and let me know what you think.
